name: Build Web App to Universal APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: npm install -g @bubblewrap/cli
    
    - name: Build APK
      run: |
        rm -rf android-app
        
        # Dùng lệnh yes n để tự động trả lời 'No' cho mọi câu hỏi của Bubblewrap init
        yes n | bubblewrap init --manifest ./manifest.json --directory ./android-app --non-interactive || true
        
        cd android-app
        bubblewrap build --non-interactive
    
    - uses: actions/upload-artifact@v4
      with:
        name: dong-ho
        path: |
          android-app/app/build/outputs/apk/debug/*.apk
          android-app/app/build/outputs/apk/release/*.apk
          
